/* Basic types shared by every part of Services.
 *
 * IRC Services is copyright (c) 1996-2009 Andrew Church.
 *     E-mail: <achurch@achurch.org>
 * Parts written by Andrew Kempe and others.
 * This program is free but copyrighted software; see the file GPL.txt for
 * details.
 *
 * This is the bottom of the include graph: configuration, the basic
 * macros of defs.h, and the typedefs of the main structures, which refer
 * to each other and so must all be declared before any is defined.  The
 * headers that services.h pulls in include this one rather than
 * services.h itself, so each of them can be parsed on its own.
 */

#ifndef TYPES_H
#define TYPES_H

/* System configuration (generated by CMake): */
#include "config.h"

/* User configuration and basic constants, macros, and includes: */
#include "defs.h"

/*************************************************************************/
/*************************************************************************/

/* Types corresponding to various structures.  These have to come first
 * because some structures reference each other circularly. */

typedef struct user_ User;
typedef struct channel_ Channel;
typedef struct server_ Server;
typedef struct serverstats_ ServerStats;

typedef struct nickinfo_ NickInfo;
typedef struct nickgroupinfo_ NickGroupInfo;
typedef struct channelinfo_ ChannelInfo;
typedef struct memoinfo_ MemoInfo;

/* Types for various name buffers, so we can make arrays of them. */

typedef char nickname_t[NICKMAX];
typedef char channame_t[CHANMAX];

/*************************************************************************/

/* Suspension info structure. */

typedef struct suspendinfo_ SuspendInfo;
struct suspendinfo_ {
    char who[NICKMAX]; /* who added this suspension */
    char* reason;
    time_t suspended;
    time_t expires; /* 0 for no expiry */
};

/*************************************************************************/

/* Constants for "what" parameter to clear_channel(). */

#define CLEAR_MODES   0x0001 /* Binary modes */
#define CLEAR_BANS    0x0002 /* Bans */
#define CLEAR_EXCEPTS 0x0004 /* Ban exceptions (no-op if not supported) */
#define CLEAR_INVITES 0x0008 /* Invite masks (no-op if not supported) */
#define CLEAR_UMODES  0x0010 /* User modes (+v, +o) */

#define CLEAR_USERS 0x8000 /* Kick all users and empty the channel */

/* All channel modes: */
#define CLEAR_CMODES (CLEAR_MODES | CLEAR_BANS | CLEAR_EXCEPTS | CLEAR_INVITES)

/*************************************************************************/
/*************************************************************************/

#endif /* TYPES_H */
