# Ported from ircu2 (cmake/GenerateMigrations.cmake).
#
# GenerateMigrations.cmake -- turn a migrations/ directory into one C source.
#
# Run at build time by ServicesMigrations.cmake, never by hand:
#
#   cmake -DSERVICES_MIGRATIONS_DIR=<dir> -DSERVICES_SYMBOL=<name>
#         -DSERVICES_OUTPUT=<file.c> -P cmake/GenerateMigrations.cmake
#
# Every *.sql below <dir> becomes a string literal, and the lot becomes a
# NULL-terminated array of struct MigrationFile named <name>.  The .sql files
# themselves are not copied anywhere: they are compiled in, so a module or the
# core carries its migrations wherever it is installed and they can neither
# go missing nor drift away from the code they belong to.
#
# This script does NOT validate anything -- not the file names, not the
# up/down pairing, not the numbering.  That is deliberate: those rules are
# enforced when a module is loaded, so that the operator who typed
# loadmodule (or REHASH) is the one who gets told what is wrong with it.  All this does
# is record what it found, under the name it found it under.
#

if(NOT SERVICES_MIGRATIONS_DIR OR NOT SERVICES_SYMBOL OR NOT SERVICES_OUTPUT)
  message(FATAL_ERROR
    "GenerateMigrations: SERVICES_MIGRATIONS_DIR, SERVICES_SYMBOL and SERVICES_OUTPUT "
    "are all required")
endif()

# _services_c_string(<text> <out>)
#
# Escapes <text> into the body of a C string literal, split one line per
# source line so that the generated file can be read and diffed.
function(_services_c_string text out)
  string(REPLACE "\\" "\\\\" escaped "${text}")
  string(REPLACE "\"" "\\\"" escaped "${escaped}")
  string(REPLACE "\r" "" escaped "${escaped}")
  string(REPLACE "\n" "\\n\"\n  \"" escaped "${escaped}")

  set(${out} "${escaped}" PARENT_SCOPE)
endfunction()

file(GLOB sql_files "${SERVICES_MIGRATIONS_DIR}/*.sql")
list(SORT sql_files)

set(body "")
set(table "")
set(index 0)

foreach(sql_file IN LISTS sql_files)
  get_filename_component(basename "${sql_file}" NAME)

  file(READ "${sql_file}" contents)
  file(SIZE "${sql_file}" size)
  string(LENGTH "${contents}" length)

  # file(READ) stops making sense at a NUL byte, and a migration is text.
  # Catching it here beats emitting a silently truncated statement.
  if(NOT length EQUAL size)
    # A CRLF file reads shorter than it is on disk on some platforms, which
    # is fine; anything else is not.
    string(REGEX MATCHALL "\r" carriage "${contents}")
    list(LENGTH carriage ncarriage)
    math(EXPR adjusted "${length} + ${ncarriage}")
    if(NOT adjusted EQUAL size)
      message(FATAL_ERROR
        "${sql_file}: not a text file (read ${length} of ${size} bytes); "
        "a migration must be SQL, not binary")
    endif()
  endif()

  _services_c_string("${contents}" literal)

  string(APPEND body
    "/* ${basename} */\n"
    "static const char services_migration_sql_${index}[] =\n"
    "  \"${literal}\";\n\n")

  string(APPEND table
    "  { \"${basename}\", services_migration_sql_${index} },\n")

  math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${SERVICES_OUTPUT}"
"/* Generated by cmake/GenerateMigrations.cmake -- do not edit.
 *
 * Source: ${SERVICES_MIGRATIONS_DIR}
 *
 * Every migration in that directory, embedded verbatim.  The names are the
 * file names as they were found; migration.c parses and validates them when
 * the module is loaded, and refuses the load if they do not follow the
 * rules in doc/readme.migrations.
 */
#include \"migration.h\"

${body}/** Every migration file, in the order the directory listed them. */
const struct MigrationFile ${SERVICES_SYMBOL}[] = {
${table}  { 0, 0 }
};
")
